// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZgzlMs0UHemBR12qAG_pz9w16y0k93l8',
    appId: '1:850416335238:web:4c6f598b126b5c782f9407',
    messagingSenderId: '850416335238',
    projectId: 'quick-count-estimator',
    authDomain: 'quick-count-estimator.firebaseapp.com',
    storageBucket: 'quick-count-estimator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXOa9xa34vdRQeCKa7eVi2DNCFwFaIok',
    appId: '1:850416335238:android:c1366e1309e69d662f9407',
    messagingSenderId: '850416335238',
    projectId: 'quick-count-estimator',
    storageBucket: 'quick-count-estimator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvbtEcd1CHWamGmTt3pV9BUoMRfKPihvA',
    appId: '1:850416335238:ios:70e1c3936ad25e792f9407',
    messagingSenderId: '850416335238',
    projectId: 'quick-count-estimator',
    storageBucket: 'quick-count-estimator.firebasestorage.app',
    iosBundleId: 'com.example.quickCountEstimator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvbtEcd1CHWamGmTt3pV9BUoMRfKPihvA',
    appId: '1:850416335238:ios:70e1c3936ad25e792f9407',
    messagingSenderId: '850416335238',
    projectId: 'quick-count-estimator',
    storageBucket: 'quick-count-estimator.firebasestorage.app',
    iosBundleId: 'com.example.quickCountEstimator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZgzlMs0UHemBR12qAG_pz9w16y0k93l8',
    appId: '1:850416335238:web:608e8c594fe805042f9407',
    messagingSenderId: '850416335238',
    projectId: 'quick-count-estimator',
    authDomain: 'quick-count-estimator.firebaseapp.com',
    storageBucket: 'quick-count-estimator.firebasestorage.app',
  );
}
